Create `eslint.config.js` (`eslint@v9`)
SAP-samples/cloud-cap-samples pull request #708
Opened 2024-04-11 11:36 UTC by mnkiefer

- Requires release of `@sap/eslint-plugin-cds@v2.7.0`

2024-04-11 16:31 UTC, daogrady approved these changes

2024-04-11 17:27 UTC, bugwelle approved these changes

2024-04-15 05:36 UTC, bugwelle requested changes

2024-04-15 05:36 UTC, bugwelle commented on eslint.config.js
> +}
```suggestion
module.exports = [{
  "files": ["**/*.js"],
  ...js.configs.recommended,
  "languageOptions": {
    "globals": {
      ...globals.browser,
      ...globals.node,
      ...globals.jest,
      ...globals.mocha,
      "es2022": true
  },
  "rules": {
    ...js.configs.recommended.rules,
    "no-console": "off",
    "require-atomic-updates": "off",
    "require-await": "warn",
    "no-unused-vars": ["warn", { "argsIgnorePattern": "_" }]
  }
},
{ 
  "files": ['**/*.cds', '**/*.csn', '**/*.csv'],
  ...cds.configs.recommended,
  "plugins": {
    "@sap/cds": cds
  },
  "languageOptions": {
    globals: {
      ...cds.globals
    }
  }
}]
```

=> you forgot the braces. :)

2024-04-15 06:01 UTC, mnkiefer commented on eslint.config.js
> +}
Thanks, Andre! 👍

2024-04-15 06:55 UTC, bugwelle approved these changes

2024-04-15 07:38 UTC, chgeo commented on package.json
> +  "peerDependencies": {
Why not a devDependency?  peerDependencies is for plugins, but cap-samples is an app.
Also, why not open it up to eslint 9, e.g. use `>=8` ?

2024-04-16 14:39 UTC, mnkiefer commented
Now at https://github.com/SAP-samples/cloud-cap-samples/pull/711

2024-04-16 14:39 UTC, closed without merging